# AMQP Constants
DEAD_LETTER_EXCHANGE = 'hares.dead-letter'
DEAD_LETTER_QUEUE = 'hares.dead-letter-queue'

INVENTORY_SERVICE = 'inventory-service'
DELIVERY_SERVICE = 'delivery-service'
CUSTOMER_SERVICE = 'customer-service'
PEOPLE_SERVICE = 'people-service'
ORDER_SERVICE = 'order-service'
LOGS_SERVICE = 'logs-service'
NOTIFICATION_SERVICE = 'notification-service'

ORDER_CREATED = 'order.created'
ORDER_SHIPPED = 'order.shipped'
ORDER_DELIVERED = 'order.delivered'
LOGS_ORDER_CREATED = 'logs.order.created'
LOGS_ORDER_UPDATED = 'logs.order.updated'
LOGS_ORDER_DELETED = 'logs.order.deleted'
LOGS_CUSTOMER_CREATED = 'logs.customer.created'
LOGS_CUSTOMER_UPDATED = 'logs.customer.updated'
LOGS_CUSTOMER_DELETED = 'logs.customer.deleted'
LOGS_SERVICE_ROUTING_KEY = 'logs.*.*'

ORDER_SERVICE_CREATED_QUEUE = 'order-service.created'
ORDER_SERVICE_UPDATED_QUEUE = 'order-service.updated'
ORDER_SERVICE_DELETED_QUEUE = 'order-service.deleted'
CUSTOMER_SERVICE_CREATED_QUEUE = 'customer-service.created'
CUSTOMER_SERVICE_UPDATED_QUEUE = 'customer-service.updated'
CUSTOMER_SERVICE_DELETED_QUEUE = 'customer-service.deleted'
LOGS_SERVICE_QUEUE = 'logs-service-q'
